default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: hayato0322
  password: hayato0322
  host: localhost

development:
  <<: *default
  database: team_todo_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: team_todo_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: team_todo_production
  username: team_todo_app
  password: <%= ENV['TEAM_TODO_DATABASE_PASSWORD'] %>
